steps:
  build_and_deploy:
    image: docker/compose:1.29.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker-compose -f docker/docker-compose.staging.yml -p datamap_calculateur up -d --build --remove-orphans
