steps:
  build_and_deploy_staging:
    image: docker/compose:1.29.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker-compose -f docker/docker-compose.staging.yml -p datamap_calculateur down --remove-orphans --rmi local
      - docker-compose -f docker/docker-compose.staging.yml -p datamap_calculateur up -d --build --force-recreate
    when:
      event: push
      branch: dev

  build_and_deploy_prod:
    image: docker/compose:1.29.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker-compose -f docker/docker-compose.yml -p datamap_calculateur_prod down --remove-orphans --rmi local || echo "warning: down failed"
      - docker-compose -f docker/docker-compose.yml -p datamap_calculateur_prod up -d --build --force-recreate
    when:
      event: push
      branch: main
