version: '3.8'

services:
  calculateur_staging:
    build:
      context: ..
      dockerfile: Dockerfile
    expose:
      - "8501"
    networks:
      - calculateur_staging_net
    restart: unless-stopped
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLE_CORS=false

networks:
  calculateur_staging_net:
    external: true
